Feature/#43/register tags
enpitut2020/Hobeeeeee pull request #47
Opened 2020-12-09 06:55 UTC by niwabarubossa

## 変更内容

記事を書いたときに

趣味が新規だったらその趣味のdocumentを作成

趣味が既存だったら、その趣味のvolumeをupdate

この２つの関数を実装

## Issue

#43

2020-12-09 07:28 UTC, KindMaple commented
a

2020-12-09 07:31 UTC, Kurorie reviewed
実装してくれた関数を使用する処理も書いて欲しいです。多分

2020-12-09 08:17 UTC, niwabarubossa commented
@Kurorie 
確かに！失礼した＞＜


実装する時は draft.js に追加

```
let inputTag = "サーフィン" 
//ここは説明のためひとまずハードコーディング。
//実装時は　<input class="input" placeholder="タグ" v-model="tags" /> から取得

let inputTagId = existTag(inputTag) 
if inputTagId == null {
 createTag(inputTag)
}else{
 updateTag(inputTagId)
}

```

2020-12-09 08:58 UTC, KindMaple commented
existTag → existingTag
のほうが自然だと思う！

2020-12-09 09:12 UTC, niwabarubossa commented
確かに！！修正します！

2020-12-09 10:11 UTC, mei28 requested changes
firebaseUtils 138行目，172行目をかつやのコメント通り修正すればおけ！GJ！！

2020-12-11 05:04 UTC, Hotsukai approved these changes
よさそう!!!

2020-12-11 05:37 UTC, Hotsukai commented on plugins/firebaseUtils.js
> +  return tagId
ここ
```
const tags=[]
～中略～
  querySnapshot.forEach(function(doc) {
      tags.push(doc.data())
    });
～中略～
return tags
```
ってしたほうが再利用性高そうな気がする。
tagオブジェクトをreturnすれば`tag.name`を使ってサジェストとかできるし

2020-12-11 05:37 UTC, Hotsukai commented on plugins/firebaseUtils.js
> +  await db.collection("tags").where("name", "==", query)
[この記事](https://note.com/shogoyamada/n/n8fe9486fcbec)みたいにすればAlgoliaなしで先頭一致で検索できて手軽にUX良くなりそう

2020-12-11 05:47 UTC, mei28 approved these changes
ありがとう！

2020-12-11 06:37 UTC, merged