cssデザイン ※作業中
enpitut2020/Hobeeeeee pull request #96
Opened 2021-01-10 16:21 UTC by nanaka0012

## 変更内容

途中経過が見えるようにドラフトPRを出しておきます
現在の進捗はここの下のdetailsから確認できるよ

## Issue

2021-01-12 17:51 UTC, nanaka0012 commented
すごい時間かかっちゃった、ごめん！
まだできてないところあるんだけど、全体の構成的にはひと段落したので
レビューよろしくお願いします！🙏

2021-01-13 02:52 UTC, mei28 commented
デザイン力のかまたりを感じた

感想
![image](https://user-images.githubusercontent.com/51149822/104399584-4d940880-5594-11eb-9b53-b79d2321a977.png)

- トップ画面せんれん洗練されたけど，ハンバーガリストとかになったときに，こっかから何やれば良いかわかんない．
- 昔みたいに趣味を探す，記事を書くボタンあった方がいいのかな？
- 個人的には記事を書く -> 趣味を書くにしたい


![image](https://user-images.githubusercontent.com/51149822/104400214-82ed2600-5595-11eb-9835-789a73437416.png)

- アイコン，フォントがかわ可愛くてよい，ずぶずぶボタンも色付きで良きかな

![image](https://user-images.githubusercontent.com/51149822/104399805-c1ceac00-5594-11eb-85a5-932aafdb90ac.png)

- タグがタグらしくなって入れよき
- ずぶずぶぼたん，tweetボタンが上にきたから押しやすそう！

![image](https://user-images.githubusercontent.com/51149822/104400020-330e5f00-5595-11eb-91ad-24ccd0a7a1af.png)
- タグ機能洗練されている！
- ここも 記事を書く -> 趣味を書くにしたい

---

すごいっす，さすがっす！！

2021-01-13 02:57 UTC, mei28 commented
Andorid10 P20でもスマホでぐりぐりとタップきちんとできていたよ

2021-01-13 02:58 UTC, mei28 approved these changes
ふーん，やるじゃん

2021-01-13 03:11 UTC, KindMaple commented
めちゃめちゃ良いやん！！
感動😂
デザイナー魂を感じた！

2021-01-13 03:17 UTC, KindMaple requested changes

2021-01-13 03:17 UTC, KindMaple commented on components/Navbar.vue
> +          >
`v-on:click="reloadTargetTag"`を追加して、「趣味を探す」を押すたびに表示される趣味を入れ変えた方が良いと思う！

2021-01-13 05:49 UTC, Hotsukai commented
えめちゃすごい!!!
コミット数がとんでもねぇありがとう!!

2021-01-13 07:40 UTC, KindMaple approved these changes
良き良き😁
お疲れ様！

2021-01-13 07:41 UTC, merged